# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tags/随笔/

# SubNav
subnav:
  github: https://github.com/flayone
  weibo: http://weibo.com/p/1005051572836850/home?from=page_100505&mod=TAB&is_all=1
  rss: "#"
  zhihu: https://www.zhihu.com/people/li-ya-yu-33
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: "https://avatars3.githubusercontent.com/u/11844888?v=3&u=c863a339b87d7a13ec318863f6006072d6bd522e&s=140"

#你的头像url
avatar: "https://avatars3.githubusercontent.com/u/11844888?v=3&u=c863a339b87d7a13ec318863f6006072d6bd522e&s=140"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: carrotfishing
#是否开启云标签
tagcloud: true
#多说评论站点
duoshuo_shortname: carrotfishing

#是否开启友情链接
#不开启——
friends: false
#开启——
friends:
  

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: android程序猿一只，求勾搭~

index_generator:
  per_page: 5

archive_generator:
  per_page: 200
  yearly: true  
  monthly: true 

tag_generator:
  per_page: 10 

category_generator: 
  per_page: 10
